---
- name: Install prerequisites
  apt: name={{ item }} state=latest
  become: true
  with_items:
    - openjdk-8-jre
    - unzip

- name: Identify JAVA_HOME
  shell: >
    update-alternatives --query java | grep 'Value: ' | grep -o '/.*/jre'
  register: java_home

- name: Add JAVA_HOME to environment variables
  lineinfile:
    path: /etc/environment
    line: "export JAVA_HOME={{ java_home.stdout }}"
    insertafter: EOF
    state: present
  become: true

- name: Source environment variables file
  shell: . /etc/environment
  become: true

- name: Has GRAKN been downloaded?
  stat: path=~/grakn
  register: grakn_path_exists

- name: Download and unzip GRAKN
  unarchive:
    src: https://grakn.ai/download/latest
    dest: ~/
    remote_src: true
  when: not grakn_path_exists.stat.isdir

- name: Find GRAKN folder name
  find:
    paths: ~/
    pattern: grakn*
    file_type: directory
  register: grakn_path
  when: not grakn_path_exists.stat.isdir

- name: Rename GRANK folder
  command: "mv {{ grakn_path.files.0.path }} grakn"
  when: not grakn_path_exists.stat.isdir
