---
- name: install aptitude
  become: true
  apt: name=aptitude state=latest

- name: update apt packages
  become: true
  apt:
    update_cache=yes
    cache_valid_time=3600

- name: upgrade apt packages
  become: true
  apt: upgrade=yes

- name: Install Java
  become: true
  apt: name=openjdk-8-jre state=latest
